### ISSUE TITLE
Null reference error

### ISSUE THREAD

**Issue by Tony20221** [unrealbg/BlazorBlog#1]
Where's the AdminUser section in the appsettings file? This is causing a null reference error because it's null

this._adminUserSettings = config.GetSection("AdminUser").Get<AdminUserSettings>();

if (await this._roleManager.FindByNameAsync(this._adminUserSettings.Role) is null)  <- error here

**Comment by unrealbg** [comment]
Hello,

Thank you for pointing out this issue. Our application is still in development, and certain sections, including the AdminUser in the appsettings.json file, are still undergoing optimization and addition.

To resolve the issue you're encountering, you can add the following code to your appsettings.json file:
```bash
 "AdminUser": {
   "Name": "Name",
   "Email": "admin@blazorblog.com",
   "Password": "Admin@123",
   "Role": "Admin"
 },
```
This will create the necessary configuration for AdminUser, required for the application to function properly at this stage. In the future, this section may be modified or expanded to meet additional requirements.

Thank you for your patience and support as we work to improve our product.

Best regards,
UnrealBG

**Comment by Tony20221** [comment]
Thanks. My personal expectation is that a public repo would run without errors, even if under development.

**Comment by unrealbg** [comment]
Thank you for your feedback. I completely agree that a public repository should run without critical errors, even in its development stages. It's important to provide a smooth experience for users who might be trying out or contributing to the project.

I will take steps to improve this aspect of the project. This will include:

1. **Updating Documentation:** I'll make sure the `README` and other documentation clearly state the current development status and provide detailed setup instructions.
2. **Providing Default Configurations:** A default `appsettings.json` with placeholder values will be added to the repository to facilitate an easier initial setup.
3. **Enhancing Error Handling:** I will work on improving error handling and logging within the application to provide clearer guidance on any missing configurations or potential issues.
4. **Implementing Continuous Integration:** If not already in place, I will set up continuous integration to ensure that each commit builds and runs without errors.
5. **Using Version Tagging:** Different stages of the project's stability and development will be clearly marked using version tags.

I appreciate your patience and understanding as these improvements are implemented. Your input is invaluable in making this project better for everyone involved.

Best regards,
UnrealBG
