### ISSUE TITLE
Fail create post

### ISSUE THREAD

**Issue by BenCG3** [unrealbg/BlazorBlog#2]
I have tried, nothing is modified to just post one blogpost and i have this error :
` Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[@p0='?' (DbType = Int32), @p1='?' (Size = 4000), @p2='?' (DbType = DateTime2), @p3='?' (Size = 4000), @p4='?' (Size = 500), @p5='?' (DbType = Boolean), @p6='?' (DbType = Boolean), @p7='?' (DbType = Boolean), @p8='?' (DbType = DateTime2), @p9='?' (Size = 125), @p10='?' (Size = 100), @p11='?' (Size = 450), @p12='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
      SET IMPLICIT_TRANSACTIONS OFF;
      SET NOCOUNT ON;
      INSERT INTO [BlogPosts] ([CategoryId], [Content], [CreatedAt], [Image], [Introduction], [IsDeleted], [IsFeatured], [IsPublished], [PublishedAt], [Slug], [Title], [UserId], [ViewCount])
      OUTPUT INSERTED.[Id]
      VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12);

fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'BlazorBlog.Data.ApplicationDbContext'.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
       ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'Image', table 'BlazorBlog.dbo.BlogPosts'; column does not allow nulls. INSERT fails.
         at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
         at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
         at Microsoft.Data.SqlClient.SqlDataReader.ReadAsyncExecute(Task task, Object state)
         at Microsoft.Data.SqlClient.SqlDataReader.InvokeAsyncCall[T](SqlDataReaderBaseAsyncCallContext`1 context)
      --- End of stack trace from previous location ---`

A problem with the image upload it's look like

**Comment by unrealbg** [comment]
Hello,

Thank you for reporting this issue. Based on the error description, it seems that the attempt to insert a record into the `BlogPosts` table is failing because the `Image` column value is `NULL`, which causes an error as this column does not allow `NULL` values.

One way to address this problem is by modifying the `BlogPost` model to include Data Annotations that enforce the `Image` as a mandatory field. I suggest adding the following attributes to the `Image` property in your model:

```csharp
[Required(ErrorMessage = "The image is required.")]
[MaxLength(100, ErrorMessage = "The length of the image URL cannot exceed 100 characters.")]
public string Image { get; set; }
```

With these changes applied, the application will require users to provide an image. This should prevent the error you are encountering.

Please try this solution and let me know if it resolves the issue.

**Comment by BenCG3** [comment]
"_fileToUpload" is always null, even when i upload a file, thats the problem.
When i try for ex an url (bypassing if (_fileToUpload is not null)) it is working with the url.
I gonna search more deep tomorow
` private async Task HandleFileUploadAsync(InputFileChangeEventArgs e)
 {
     Console.WriteLine("Nombre d'image : "+ e.FileCount.ToString());
     await PreviewImageAsync(e.File);
     _fileToUpload = e.File;<=== return nothing
 }`
I think it's the problem, i have 1 count but it is not working.
Sory for my bad English.

**Comment by BenCG3** [comment]
Ok so easy enough, wrapping the Task "PreviewImageAsync" with IOException i find out that the maximum file upload is set by defaut on 500kb... I feel dumb right now.
i just adjust imageStream limitation size to in my case is 10mb for ex :
`using var imageStream = file.OpenReadStream(maxAllowedSize:10000000)`
End it's working like a charm.

**Comment by unrealbg** [comment]
Hello,

Thank you for sharing the details regarding the issues you've encountered. I wanted to inform you that I have made several changes to the code that address these concerns. These changes include improvements to the `SaveBlogPost` component for more efficient content and image handling, as well as optimization of the file upload process. These updates have already been uploaded to the repository.

Additionally, I have taken into account your remark about the size limitation of image files. I have implemented a fix that increases the maximum size of uploaded files to 10MB. This should enhance functionality and provide more flexibility when working with images. Appropriate user messages have also been included to inform about this limit to avoid any confusion.

Please review the changes and provide your feedback. Your insights and suggestions are valuable for the continuous improvement of the project.

Thank you again for your contribution and support.

Best regards,
unrealbg

**Comment by BenCG3** [comment]
Hello you need also a change in Task SaveFileAsync because it cause the same issue (again "OpenReadStream"):
I have created a public ref :  
`public long MaxFileLenght = 10 * 1024 * 1024; `
For saving the file :
` await file.OpenReadStream(maxAllowedSize: MaxFileLenght).CopyToAsync(fs);`
For the preview i use MaxFileLenght to.
For the preview you have already do the change nice, i see more check for errors and some improvement in new version thats great !
No problem 👍

**Comment by unrealbg** [comment]
Hello,

Thank you for pointing out the need for a change in the `SaveFileAsync` method in relation to the file size limitation issue. I appreciate your vigilance in identifying that this method also requires the same adjustment as the `PreviewImageAsync` method.

I have implemented the suggested modification:

```csharp
private async Task<string?> SaveFileAsync(IBrowserFile file)
{
    var webRootPath = WebHostEnvironment.WebRootPath;
    var folderPath = Path.Combine(webRootPath, "images", "posts");
    Directory.CreateDirectory(folderPath);

    var randomFileName = Path.GetRandomFileName();
    var extension = Path.GetExtension(file.Name);
    var filePath = Path.Combine(folderPath, randomFileName + extension);

    await using FileStream fs = new(filePath, FileMode.Create);

    try
    {
        await file.OpenReadStream(maxAllowedSize: MaxFileLenght).CopyToAsync(fs);
        return Path.Combine("images", "posts", randomFileName + extension).Replace("\\", "/");
    }
    catch (Exception)
    {
        ToastService.ShowToast(ToastLevel.Error, "Something went wrong while saving the file.", heading: "Error");
        fs.Close();
        return null;
    }
}
```
I've now incorporated the MaxFileLenght constant to both the SaveFileAsync and PreviewImageAsync methods, ensuring consistency across the file handling process.

I'm glad to hear that the other improvements and error checks in the new version are to your satisfaction. Your feedback is invaluable in making our project more robust and user-friendly.

Please do not hesitate to reach out if there are any more suggestions or issues.

Best regards,

unrealbg
